spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aircnc?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${db.username:root}
    password: ${db.password:1234}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    default-encoding: UTF-8
    port: 465
    protocol: smtp
    host: "smtp.gmail.com"
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            fallback: false
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enabled: true
            required: true

jwt:
  issuer: "gurudev"
  client-secret: ${jwt.client.secret:secret}
  expiry-seconds: 1800

room-photos:
  path: src/main/resources/room-photos/
