spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aircnc?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${db.username:gurudev}
    password: ${db.password:pass123}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  issuer: ${jwt.issuer:issuer}
  client-secret: ${jwt.client.secret:secret}
  expiry-seconds: 1800

room-photos:
  path: src/main/resources/room-photos/
